apiVersion: v1
kind: Service
metadata:
  name: minio-spring-service
spec:
  selector:
    app: minio-spring-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort